/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MediaMetadata {
  title: string
  artist: string
  album: string
  duration: number
}
export class MediaControl {
  constructor()
  setMetadata(metadata: MediaMetadata): void
  attach(callback: (event: 'play' | 'pause' | 'next' | 'previous' | 'stop' | 'toggle') => void): void
  setState(playing_state: 'playing' | 'paused' | 'stopped', progress?: number): void
}
