[package]
edition = "2021"
name = "fentio"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.10.2", default-features = false, features = ["napi4"] }
napi-derive = "2.9.3"
once_cell = "1.17.0"
rodio = "0.16.0"

[dependencies.uuid]
version = "1.2.2"
features = ["v4", "fast-rng"]

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
