name: Checks

on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  compile:
    name: 🏗️ compile app
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: cache rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./packages/fentio/.cargo-cache
            ./packages/fentio/target
            ./packages/ktm/.cargo-cache
            ./packages/ktm/target
          key: cargo

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1

      - name: setup toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabihf libasound2-dev build-essential libdbus-glib-1-dev libgirepository1.0-dev -y
        shell: bash

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: node deps
        run: yarn --immutable

      - name: build everything
        run: yarn build
